In [2]:
import pandas as pd
import numpy as np

In [11]:
my_list = [[4],[5],[78],[32],[29],[54]]

In [13]:
array = np.array(my_list)

In [14]:
[x*x for x in array]

[array([16]),
 array([25]),
 array([6084]),
 array([1024]),
 array([841]),
 array([2916])]

In [16]:
list_a = [1,3,56,6,3]
list_b = [4,7,6,32,3]
list_c = [list_a, list_b]
list_c

[[1, 3, 56, 6, 3], [4, 7, 6, 32, 3]]

In [17]:
import requests

In [32]:
def get_name(name):
    parameters = {"name":name}
    response = requests.get(
    "http://localhost:8000/hello-name",
    params=parameters).json()

    return response

In [33]:
get_name("Oliver")

{'Hello ': 'Oliver!'}

In [149]:
data = pd.read_csv("/Users/james/code/lucasglanville/and_theyre_off_frontend/interface/data_cleaned_and_preprocessed_v3.csv",usecols = ['f_ko', 'pred_isp'] )

In [150]:
data

f_ko  pred_isp
0       2021-03-06 01:25:00  0.400000
1       2021-03-06 01:25:00  0.222222
2       2021-03-06 01:25:00  0.181818
3       2021-03-06 01:25:00  0.133333
4       2021-03-06 01:25:00  0.090909
...                     ...       ...
117463  2023-08-20 18:45:00  0.090909
117464  2023-08-20 18:45:00  0.090909
117465  2023-08-20 18:45:00  0.090909
117466  2023-08-20 18:45:00  0.076923
117467  2023-08-20 18:45:00  0.076923

[117468 rows x 2 columns]

In [12]:
pd.set_option('display.max_columns', None)

In [145]:
cols = ['f_ko', 'pred_isp']
data = data[cols]
data["required_odds"] = round(1/(data.pred_isp/1.1),2)
data

f_ko  pred_isp  required_odds
0       2021-03-06 01:25:00  0.400000           2.75
1       2021-03-06 01:25:00  0.222222           4.95
2       2021-03-06 01:25:00  0.181818           6.05
3       2021-03-06 01:25:00  0.133333           8.25
4       2021-03-06 01:25:00  0.090909          12.10
...                     ...       ...            ...
117463  2023-08-20 18:45:00  0.090909          12.10
117464  2023-08-20 18:45:00  0.090909          12.10
117465  2023-08-20 18:45:00  0.090909          12.10
117466  2023-08-20 18:45:00  0.076923          14.30
117467  2023-08-20 18:45:00  0.076923          14.30

[117468 rows x 3 columns]

In [146]:
import decimal

decimal_object = decimal.Decimal(data['required_odds'][0])

numerator, denominator = decimal_object.as_integer_ratio()
numerator, denominator

(11, 4)

In [65]:
data = pd.read_csv("/Users/james/Downloads/hr_data_0409_221rem.csv")
data.head()

/var/folders/zf/gnbkqzzn3ns4_tq1g95vbnd40000gn/T/ipykernel_63768/3360362142.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/james/Downloads/hr_data_0409_221rem.csv")


id          f_id              f_ko     f_track f_going  \
0  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
1  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
2  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
3  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
4  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   

       f_racetype          f_horse              f_jockey        f_trainer  \
0  Other Handicap  Tone The Barone            Ryan Moore  Stuart Williams   
1  Other Handicap      Royal Birth          Marco Ghiani  Stuart Williams   
2  Other Handicap            Lihou    Pierre-Louis Jamin      David Evans   
3  Other Handicap     Marnie James            Ben Curtis      Scott Dixon   
4  Other Handicap     Blue De Vega  Benoit De La Sayette    Robert Cowell   

   f_distance  f_class  f_age  f_pace  f_weight  f_runners  pred_isp  \
0         5.0      2.0      5     7.0       126          7       2.5   
1         5.0      2.0     10     4.0       126          7      13.0   
2         5.0      2.0      5     6.0       121          7       5.5   
3         5.0      2.0      6     7.0       126          7      17.0   
4         5.0      2.0      8     5.0       134          7       4.5   

   f_rating_rbd  f_rating_or  f_stall f_rating_hc  f_dob  f_prb_avg  \
0         154.0           95      2.0         NaN    NaN        NaN   
1         131.0           95      5.0         NaN    NaN        NaN   
2         145.0           89      3.0         NaN    NaN        NaN   
3         123.0           95      1.0         NaN    NaN        NaN   
4         142.0          102      6.0         NaN    NaN        NaN   

   f_lto_pos f_headgear  f_place  f_bsp  f_pm_15m  f_pm_10m  f_pm_05m  \
0        NaN          T        3   2.08       1.9      1.93      1.81   
1        NaN          T        4  13.62      20.0     21.00     21.00   
2        NaN        NaN        2   5.20       6.0      5.90      5.90   
3        NaN        NaN        7  17.75      21.0     21.00     21.00   
4        NaN          T        6  10.50       8.2      7.60      9.80   

   f_pm_03m  f_pm_02m  f_pm_01m  f_bsp_p_back  f_bsp_p_lay  f_pm_01m_p_back  \
0      1.89       2.1      2.28          -1.0         0.95             -1.0   
1     17.00      17.0     12.50          -1.0         0.95             -1.0   
2      5.90       5.4      5.60          -1.0         0.95             -1.0   
3     18.50      17.0     15.00          -1.0         0.95             -1.0   
4     10.50       9.4     10.00          -1.0         0.95             -1.0   

   f_pm_01m_p_lay  f_pm_15m_p_back  f_pm_15m_p_lay  trainer_runs_win_at  \
0            0.95             -1.0            0.95                  0.0   
1            0.95             -1.0            0.95                  0.0   
2            0.95             -1.0            0.95                  2.0   
3            0.95             -1.0            0.95                  0.0   
4            0.95             -1.0            0.95                  0.0   

   trainer_runs_win_l200r  trainer_runs_win_l50r  trainer_runs_win_l16r  \
0                     0.0                    0.0                    0.0   
1                     0.0                    0.0                    0.0   
2                     2.0                    2.0                    2.0   
3                     0.0                    0.0                    0.0   
4                     0.0                    0.0                    0.0   

   trainer_runs_at  trainer_runs_l200r  trainer_runs_l50r  trainer_runs_l16r  \
0              5.0                 5.0                5.0                5.0   
1              6.0                 6.0                6.0                6.0   
2              2.0                 2.0                2.0                2.0   
3              1.0                 1.0                1.0                1.0   
4              2.0                 2.0         

In [66]:
def extract_date(x):
    return x[:10]

def extract_time(x):
    return x[11:]

data['date'] = data['f_ko'].apply(extract_date)
data['time'] = data['f_ko'].apply(extract_time)

In [102]:
data[['pred_isp']]

pred_isp
0            2.5
1           13.0
2            5.5
3           17.0
4            4.5
...          ...
120670       7.5
120671      15.0
120672      11.0
120673      26.0
120674      13.0

[120675 rows x 1 columns]

In [115]:
type(data[['pred_isp']])

pandas.core.frame.DataFrame

In [121]:
from fractions import Fraction
x = Fraction(str((data.pred_isp[0])))
print(type(x))


<class 'fractions.Fraction'>


In [122]:
def float_to_integer(x):
    ratio = x.as_integer_ratio()
    return f'{ratio[0]}/{ratio[1]}'
float_to_integer

In [116]:
def float_to_integer(x):
    ratio = x.as_integer_ratio()
    num = ratio[0]
    den = ratio[1]
    return f'{num}/{den}'
data['pred_isp'] = data['pred_isp'].apply(float_to_integer)
data["pred_isp"]

0          5/2
1         13/1
2         11/2
3         17/1
4          9/2
          ... 
120670    15/2
120671    15/1
120672    11/1
120673    26/1
120674    13/1
Name: pred_isp, Length: 120675, dtype: object

In [81]:
len(data)

120675

In [119]:
5.5 %1

0.5