In [2]:
import pandas as pd
import numpy as np

In [11]:
my_list = [[4],[5],[78],[32],[29],[54]]

In [13]:
array = np.array(my_list)

In [14]:
[x*x for x in array]

[array([16]),
 array([25]),
 array([6084]),
 array([1024]),
 array([841]),
 array([2916])]

In [16]:
list_a = [1,3,56,6,3]
list_b = [4,7,6,32,3]
list_c = [list_a, list_b]
list_c

[[1, 3, 56, 6, 3], [4, 7, 6, 32, 3]]

In [17]:
import requests

In [32]:
def get_name(name):
    parameters = {"name":name}
    response = requests.get(
    "http://localhost:8000/hello-name",
    params=parameters).json()

    return response

In [33]:
get_name("Oliver")

{'Hello ': 'Oliver!'}

In [149]:
data = pd.read_csv("/Users/james/code/lucasglanville/and_theyre_off_frontend/interface/data_cleaned_and_preprocessed_v3.csv",usecols = ['f_ko', 'pred_isp'] )

In [150]:
data

f_ko  pred_isp
0       2021-03-06 01:25:00  0.400000
1       2021-03-06 01:25:00  0.222222
2       2021-03-06 01:25:00  0.181818
3       2021-03-06 01:25:00  0.133333
4       2021-03-06 01:25:00  0.090909
...                     ...       ...
117463  2023-08-20 18:45:00  0.090909
117464  2023-08-20 18:45:00  0.090909
117465  2023-08-20 18:45:00  0.090909
117466  2023-08-20 18:45:00  0.076923
117467  2023-08-20 18:45:00  0.076923

[117468 rows x 2 columns]

In [144]:
pd.set_option('display.max_columns', None)

In [145]:
cols = ['f_ko', 'pred_isp']
data = data[cols]
data["required_odds"] = round(1/(data.pred_isp/1.1),2)
data

f_ko  pred_isp  required_odds
0       2021-03-06 01:25:00  0.400000           2.75
1       2021-03-06 01:25:00  0.222222           4.95
2       2021-03-06 01:25:00  0.181818           6.05
3       2021-03-06 01:25:00  0.133333           8.25
4       2021-03-06 01:25:00  0.090909          12.10
...                     ...       ...            ...
117463  2023-08-20 18:45:00  0.090909          12.10
117464  2023-08-20 18:45:00  0.090909          12.10
117465  2023-08-20 18:45:00  0.090909          12.10
117466  2023-08-20 18:45:00  0.076923          14.30
117467  2023-08-20 18:45:00  0.076923          14.30

[117468 rows x 3 columns]

In [146]:
import decimal

decimal_object = decimal.Decimal(data['required_odds'][0])

numerator, denominator = decimal_object.as_integer_ratio()
numerator, denominator

(11, 4)

In [3]:
data = pd.read_csv("/Users/james/code/lucasglanville/and_theyre_off_frontend/interface/data_cleaned_and_preprocessed_v3.csv")

In [7]:
data

f_going  average_or_rating_class  above_below_official_rating_class  \
0           0.4                 0.836105                           0.643877   
1           0.4                 0.836105                           0.691321   
2           0.4                 0.836105                           0.603211   
3           0.4                 0.836105                           0.657433   
4           0.4                 0.836105                           0.609989   
...         ...                      ...                                ...   
117463      0.4                 0.672879                           0.561825   
117464      0.4                 0.672879                           0.656712   
117465      0.4                 0.672879                           0.575380   
117466      0.4                 0.672879                           0.710933   
117467      0.4                 0.672879                           0.656712   

        PreviousPosition  PredictedRank  f_distance   f_class     f_age  \
0               0.000000       0.000000    0.000000  0.166667  0.250000   
1               0.000000       0.032258    0.000000  0.166667  0.500000   
2               0.000000       0.064516    0.000000  0.166667  0.250000   
3               0.000000       0.096774    0.000000  0.166667  0.500000   
4               0.000000       0.129032    0.000000  0.166667  0.333333   
...                  ...            ...         ...       ...       ...   
117463          0.064516       0.161290    0.545455  0.333333  0.166667   
117464          0.064516       0.193548    0.545455  0.333333  0.250000   
117465          0.129032       0.225806    0.545455  0.333333  0.250000   
117466          0.193548       0.258065    0.545455  0.333333  0.250000   
117467          0.161290       0.290323    0.545455  0.333333  0.250000   

        f_pace  f_weight  ...     f_dob  f_prb_avg            f_id  \
0          0.7  0.218750  ...  0.404181   0.434968  16149939000030   
1          0.5  0.343750  ...  0.404181   0.434968  16149939000030   
2          0.6  0.140625  ...  0.404181   0.434968  16149939000030   
3          1.0  0.250000  ...  0.404181   0.434968  16149939000030   
4          0.5  0.156250  ...  0.404181   0.434968  16149939000030   
...        ...       ...  ...       ...        ...             ...   
117463     0.6  0.078125  ...  0.300000   0.400000  16925535000012   
117464     0.6  0.296875  ...  0.500000   0.500000  16925535000012   
117465     0.8  0.109375  ...  0.340000   0.490000  16925535000012   
117466     0.3  0.437500  ...  0.410000   0.580000  16925535000012   
117467     0.4  0.296875  ...  0.310000   0.610000  16925535000012   

                       f_ko  pred_isp  f_place  f_pm_15m  f_pm_05m  f_pm_01m  \
0       2021-03-06 01:25:00  0.400000        0       1.9      1.81      2.28   
1       2021-03-06 01:25:00  0.222222        0       8.2      9.80     10.00   
2       2021-03-06 01:25:00  0.181818        0       6.0      5.90      5.60   
3       2021-03-06 01:25:00  0.133333        1      17.0     18.50     11.50   
4       2021-03-06 01:25:00  0.090909        0      28.0     28.00     17.50   
...                     ...       ...      ...       ...       ...       ...   
117463  2023-08-20 18:45:00  0.090909        0       7.6      7.80      6.80   
117464  2023-08-20 18:45:00  0.090909        1      17.5     16.50     13.00   
117465  2023-08-20 18:45:00  0.090909        0       9.4     10.50     10.50   
117466  2023-08-20 18:45:00  0.076923        0      24.0     25.00     17.50   
117467  2023-08-20 18:45:00  0.076923        0      12.0      9.40     11.50   

        f_pm_15m_p_back  
0                 -1.00  
1                 -1.00  
2                 -1.00  
3                 15.20  
4                 -1.00  
...                 ...  
117463            -1.00  
117464            15.67  
117465            -1.00  
117466            -1.00  
117467            -1.00  

[117468 rows x 164 columns]