In [2]:
import pandas as pd
import numpy as np

In [11]:
my_list = [[4],[5],[78],[32],[29],[54]]

In [13]:
array = np.array(my_list)

In [14]:
[x*x for x in array]

[array([16]),
 array([25]),
 array([6084]),
 array([1024]),
 array([841]),
 array([2916])]

In [16]:
list_a = [1,3,56,6,3]
list_b = [4,7,6,32,3]
list_c = [list_a, list_b]
list_c

[[1, 3, 56, 6, 3], [4, 7, 6, 32, 3]]

In [17]:
import requests

In [32]:
def get_name(name):
    parameters = {"name":name}
    response = requests.get(
    "http://localhost:8000/hello-name",
    params=parameters).json()

    return response

In [33]:
get_name("Oliver")

{'Hello ': 'Oliver!'}

In [149]:
data = pd.read_csv("/Users/james/code/lucasglanville/and_theyre_off_frontend/interface/data_cleaned_and_preprocessed_v3.csv",usecols = ['f_ko', 'pred_isp'] )

In [150]:
data

f_ko  pred_isp
0       2021-03-06 01:25:00  0.400000
1       2021-03-06 01:25:00  0.222222
2       2021-03-06 01:25:00  0.181818
3       2021-03-06 01:25:00  0.133333
4       2021-03-06 01:25:00  0.090909
...                     ...       ...
117463  2023-08-20 18:45:00  0.090909
117464  2023-08-20 18:45:00  0.090909
117465  2023-08-20 18:45:00  0.090909
117466  2023-08-20 18:45:00  0.076923
117467  2023-08-20 18:45:00  0.076923

[117468 rows x 2 columns]

In [12]:
pd.set_option('display.max_columns', None)

In [145]:
cols = ['f_ko', 'pred_isp']
data = data[cols]
data["required_odds"] = round(1/(data.pred_isp/1.1),2)
data

f_ko  pred_isp  required_odds
0       2021-03-06 01:25:00  0.400000           2.75
1       2021-03-06 01:25:00  0.222222           4.95
2       2021-03-06 01:25:00  0.181818           6.05
3       2021-03-06 01:25:00  0.133333           8.25
4       2021-03-06 01:25:00  0.090909          12.10
...                     ...       ...            ...
117463  2023-08-20 18:45:00  0.090909          12.10
117464  2023-08-20 18:45:00  0.090909          12.10
117465  2023-08-20 18:45:00  0.090909          12.10
117466  2023-08-20 18:45:00  0.076923          14.30
117467  2023-08-20 18:45:00  0.076923          14.30

[117468 rows x 3 columns]

In [146]:
import decimal

decimal_object = decimal.Decimal(data['required_odds'][0])

numerator, denominator = decimal_object.as_integer_ratio()
numerator, denominator

(11, 4)

In [65]:
data = pd.read_csv("/Users/james/Downloads/hr_data_0409_221rem.csv")
data.head()

/var/folders/zf/gnbkqzzn3ns4_tq1g95vbnd40000gn/T/ipykernel_63768/3360362142.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/Users/james/Downloads/hr_data_0409_221rem.csv")


id          f_id              f_ko     f_track f_going  \
0  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
1  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
2  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
3  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
4  1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   

       f_racetype          f_horse              f_jockey        f_trainer  \
0  Other Handicap  Tone The Barone            Ryan Moore  Stuart Williams   
1  Other Handicap      Royal Birth          Marco Ghiani  Stuart Williams   
2  Other Handicap            Lihou    Pierre-Louis Jamin      David Evans   
3  Other Handicap     Marnie James            Ben Curtis      Scott Dixon   
4  Other Handicap     Blue De Vega  Benoit De La Sayette    Robert Cowell   

   f_distance  f_class  f_age  f_pace  f_weight  f_runners  pred_isp  \
0         5.0      2.0      5     7.0       126          7       2.5   
1         5.0      2.0     10     4.0       126          7      13.0   
2         5.0      2.0      5     6.0       121          7       5.5   
3         5.0      2.0      6     7.0       126          7      17.0   
4         5.0      2.0      8     5.0       134          7       4.5   

   f_rating_rbd  f_rating_or  f_stall f_rating_hc  f_dob  f_prb_avg  \
0         154.0           95      2.0         NaN    NaN        NaN   
1         131.0           95      5.0         NaN    NaN        NaN   
2         145.0           89      3.0         NaN    NaN        NaN   
3         123.0           95      1.0         NaN    NaN        NaN   
4         142.0          102      6.0         NaN    NaN        NaN   

   f_lto_pos f_headgear  f_place  f_bsp  f_pm_15m  f_pm_10m  f_pm_05m  \
0        NaN          T        3   2.08       1.9      1.93      1.81   
1        NaN          T        4  13.62      20.0     21.00     21.00   
2        NaN        NaN        2   5.20       6.0      5.90      5.90   
3        NaN        NaN        7  17.75      21.0     21.00     21.00   
4        NaN          T        6  10.50       8.2      7.60      9.80   

   f_pm_03m  f_pm_02m  f_pm_01m  f_bsp_p_back  f_bsp_p_lay  f_pm_01m_p_back  \
0      1.89       2.1      2.28          -1.0         0.95             -1.0   
1     17.00      17.0     12.50          -1.0         0.95             -1.0   
2      5.90       5.4      5.60          -1.0         0.95             -1.0   
3     18.50      17.0     15.00          -1.0         0.95             -1.0   
4     10.50       9.4     10.00          -1.0         0.95             -1.0   

   f_pm_01m_p_lay  f_pm_15m_p_back  f_pm_15m_p_lay  trainer_runs_win_at  \
0            0.95             -1.0            0.95                  0.0   
1            0.95             -1.0            0.95                  0.0   
2            0.95             -1.0            0.95                  2.0   
3            0.95             -1.0            0.95                  0.0   
4            0.95             -1.0            0.95                  0.0   

   trainer_runs_win_l200r  trainer_runs_win_l50r  trainer_runs_win_l16r  \
0                     0.0                    0.0                    0.0   
1                     0.0                    0.0                    0.0   
2                     2.0                    2.0                    2.0   
3                     0.0                    0.0                    0.0   
4                     0.0                    0.0                    0.0   

   trainer_runs_at  trainer_runs_l200r  trainer_runs_l50r  trainer_runs_l16r  \
0              5.0                 5.0                5.0                5.0   
1              6.0                 6.0                6.0                6.0   
2              2.0                 2.0                2.0                2.0   
3              1.0                 1.0                1.0                1.0   
4              2.0                 2.0         

In [66]:
def extract_date(x):
    return x[:10]

def extract_time(x):
    return x[11:]

data['date'] = data['f_ko'].apply(extract_date)
data['time'] = data['f_ko'].apply(extract_time)

In [67]:
data

id          f_id              f_ko     f_track f_going  \
0       1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
1       1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
2       1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
3       1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
4       1.614990e+13  1.614990e+13  06/03/2021 01:25  LINGFIELD      STD   
...              ...           ...               ...         ...     ...   
120670  1.693760e+13  1.693760e+13  03/09/2023 17:30   TIPPERARY     YLD   
120671  1.693760e+13  1.693760e+13  03/09/2023 17:30   TIPPERARY     YLD   
120672  1.693760e+13  1.693760e+13  03/09/2023 17:30   TIPPERARY     YLD   
120673  1.693760e+13  1.693760e+13  03/09/2023 17:30   TIPPERARY     YLD   
120674  1.693760e+13  1.693760e+13  03/09/2023 17:30   TIPPERARY     YLD   

            f_racetype          f_horse              f_jockey  \
0       Other Handicap  Tone The Barone            Ryan Moore   
1       Other Handicap      Royal Birth          Marco Ghiani   
2       Other Handicap            Lihou    Pierre-Louis Jamin   
3       Other Handicap     Marnie James            Ben Curtis   
4       Other Handicap     Blue De Vega  Benoit De La Sayette   
...                ...              ...                   ...   
120670  Other Handicap      Hello Power           Colin Keane   
120671  Other Handicap        Maralinga            Gavin Ryan   
120672  Other Handicap    Global Energy         Robbie Colgan   
120673  Other Handicap           Rotolo          Neve Bennett   
120674  Other Handicap     Kings Prince               W J Lee   

               f_trainer  f_distance  f_class  f_age  f_pace  f_weight  \
0        Stuart Williams         5.0      2.0      5     7.0       126   
1        Stuart Williams         5.0      2.0     10     4.0       126   
2            David Evans         5.0      2.0      5     6.0       121   
3            Scott Dixon         5.0      2.0      6     7.0       126   
4          Robert Cowell         5.0      2.0      8     5.0       134   
...                  ...         ...      ...    ...     ...       ...   
120670        D J Bunyan        12.5      NaN      4     5.0       127   
120671     Timothy Doyle        12.5      NaN      5     9.0       133   
120672  Ms Sheila Lavery        12.5      NaN      4     3.0       142   
120673       W T Farrell        12.5      NaN      4     4.0       136   
120674  Eamonn O´Connell        12.5      NaN      5     4.0       134   

        f_runners  pred_isp  f_rating_rbd  f_rating_or  f_stall f_rating_hc  \
0               7       2.5         154.0           95      2.0         NaN   
1               7      13.0         131.0           95      5.0         NaN   
2               7       5.5         145.0           89      3.0         NaN   
3               7      17.0         123.0           95      1.0         NaN   
4               7       4.5         142.0          102      6.0         NaN   
...           ...       ...           ...          ...      ...         ...   
120670         18       7.5          89.0           55      6.0       47-70   
120671         18      15.0          86.0           60     21.0       47-70   
120672         18      11.0          73.0           70      7.0       47-70   
120673         18      26.0          85.0           63     20.0       47-70   
120674         18      13.0          88.0           61     12.0       47-70   

        f_dob  f_prb_avg  f_lto_pos f_headgear  f_place  f_bsp  f_pm_15m  \
0         NaN        NaN        NaN          T        3   2.08       1.9   
1         NaN        NaN        NaN          T        4  13.62      20.0   
2         NaN        NaN        NaN        NaN        2   5.20       6.0   
3         NaN        NaN        NaN        NaN        7  17.75      21.0   
4         NaN        NaN        NaN          T        6  10.50       8.2   
...       ...        ...      

In [59]:
data.drop(columns=['date',	'time'], inplace=True)

In [68]:
data[data.date == '03/09/2023']

id          f_id              f_ko    f_track f_going  \
120621  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120622  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120623  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120624  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120625  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120626  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120627  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120628  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120629  1.693750e+13  1.693750e+13  03/09/2023 15:00   BRIGHTON     GTS   
120630  1.693750e+13  1.693750e+13  03/09/2023 16:10   BRIGHTON     GTS   
120631  1.693750e+13  1.693750e+13  03/09/2023 16:10   BRIGHTON     GTS   
120632  1.693750e+13  1.693750e+13  03/09/2023 16:10   BRIGHTON     GTS   
120633  1.693750e+13  1.693750e+13  03/09/2023 16:10   BRIGHTON     GTS   
120634  1.693750e+13  1.693750e+13  03/09/2023 16:10   BRIGHTON     GTS   
120635  1.693750e+13  1.693750e+13  03/09/2023 16:10   BRIGHTON     GTS   
120636  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120637  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120638  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120639  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120640  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120641  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120642  1.693760e+13  1.693760e+13  03/09/2023 16:45   BRIGHTON     GTS   
120643  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120644  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120645  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120646  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120647  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120648  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120649  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120650  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120651  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120652  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120653  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120654  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120655  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120656  1.693760e+13  1.693760e+13  03/09/2023 16:55  TIPPERARY     YLD   
120657  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120658  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120659  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120660  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120661  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120662  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120663  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120664  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120665  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120666  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120667  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120668  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120669  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120670  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120671  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120672  1.693760e+13  1.693760e+13  03/09/2023 17:30  TIPPERARY     YLD   
120673  1.693760e+13  1.693760e+13  03/09/2